### ISSUE TITLE
Special handling for `time.Duration`

### ISSUE THREAD

**Issue by Elara6331** [alecthomas/repr#19]
The `time.Duration` type prints as `time.Duration(24h00m00s)` which isn't valid code.

I think the best way to fix this would be to ignore the `String()` method of `time.Duration` and instead print it as a `float64`, so 24h would be `time.Duration(8.64e+13)`, which is valid Go code.

**Comment by alecthomas** [comment]
The rationale behind the current behaviour is so that enums are represented well. That is, the same code that results in Duration displaying like this, results in enums displaying in a reasonable manner.

eg.

`repr.Enum(Value)` vs. `repr.Enum(1)`

repr doesn't aim for 100% fidelity with Go code, it also tries to be human readable where possible, and this is one of those cases where I think readability is more important, especially with duration. Showing `time.Duration(3600000000000)` is much less readable than `time.Duration(1h0m0s)`.

That said, an option to enable this behaviour would probably be useful.

**Comment by alecthomas** [comment]
Done. Give that a shot.

**Comment by Elara6331** [comment]
That works, thanks!
